### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by hmtxz** [vcheckzen/xiaomiThemeDownloader#2]
Theme link: http://zhuti.xiaomi.com/detail/29b23d56-ba48-4804-9423-be618f322678
MIUI Version: V12

Error after clicking download button

![image](https://user-images.githubusercontent.com/20640272/85944208-375b8d80-b95f-11ea-9788-28234629e4e5.png)

**Comment by vcheckzen** [comment]
Tested ok, mind give all permissions needed and not use `https`.  If can't work still, the problem can be that Xiaomi has not opened api server out of china.
